# Generated by Django 6.1.1 on 2026-09-28 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_pruefung_externe_nummern_ende_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruefungsZuweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zugewiesen_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('pruefer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungszuweisungen', to=settings.AUTH_USER_MODEL)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefer_zuweisungen', to='exams.pruefung')),
                ('zugewiesen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erteilte_prueferzuweisungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pruefung__titel', 'pruefer__last_name', 'pruefer__username'],
                'constraints': [models.UniqueConstraint(fields=('pruefung', 'pruefer'), name='unique_examiner_exam_assignment')],
            },
        ),
    ]
