# Generated by Django 6.1.1 on 2026-09-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_organisation_demo_inhalte_startbestand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einladung',
            name='rolle',
            field=models.CharField(choices=[('superadmin', 'Super-Admin'), ('org_admin', 'Org-Admin'), ('trainer', 'Trainer'), ('exam_operator', 'Prüfungsoperator'), ('examiner', 'Pruefer'), ('learner', 'Lernender')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganisationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('primaer', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Mandantendomäne',
                'verbose_name_plural': 'Mandantendomänen',
                'ordering': ['hostname'],
            },
        ),
    ]
